.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "README" "" "December 2014" "" ""
.
.SH "NAME"
\fBREADME\fR
.
.SH "kadnode(1) \- P2P name resolution daemon"
.
.SH "SYNOPSIS"
\fBkadnode\fR [\-\-value\-id identifier] [\-\-port port] [\-\-daemon] [\.\.\.]
.
.P
\fBkadnode\-ctl\fR [\.\.\.]
.
.SH "DESCRIPTION"
\fBKadNode\fR is a small P2P DNS resolution daemon based on a Distributed Hash Table (DHT)\. KadNode can intercept and resolve DNS request in the systems background\. Every instance can also announce any domain like e\.g\. myname\.p2p\. People on others devices running KadNode can then enter myname\.p2p into their browsers or console in order to reach the announcing host\. To avoid name clashes, cryptographic public/private key pairs can be used\. This makes it possible to have a personal and decentralized DynDNS service\. The DHT \fIhttps://github\.com/jech/dht\fR is identical to the one used in the Transmission Bittorrent client and works on the Internet as well as on local networks\.
.
.P
Features:
.
.IP "\(bu" 4
IPv4/IPv6 support
.
.IP "\(bu" 4
UPnP/NAT\-PMP support
.
.IP "\(bu" 4
local peer discovery
.
.IP "\(bu" 4
small size 75KB\-125KB
.
.IP "\(bu" 4
public/secret key authentication (based on libsodium \fIhttps://github\.com/jedisct1/libsodium\fR)
.
.IP "\(bu" 4
command line interface (kadnode\-ctl)
.
.IP "\(bu" 4
NSS support through /etc/nsswitch\.conf
.
.IP "\(bu" 4
integrated simplified DNS server (handles A, AAAA, and SRV requests)
.
.IP "\(bu" 4
packages for ArchLinux/Debian/FreeBSD/MacOSX/OpenWrt/Windows
.
.IP "\(bu" 4
peer file import/export on startup/shutdown and every 24h
.
.IP "" 0
.
.P
Most features are optional and can be left out to reduce the binary size\.
.
.SH "JOIN THE SWARM"
KadNode needs to know at least one active peer to join a swarm\. This can be achieved by inserting e\.g\. \fIbttracker\.debian\.org\fR, or any other address of an active peer, into a file and provide it to KadNode:
.
.IP "" 4
.
.nf

kadnode \-\-peerfile peers\.txt
.
.fi
.
.IP "" 0
.
.P
This will cause KadNode to bootstrap into a network\. On shutdown and also every 24h, KadNode writes at most 150 good peers back to the peer file\. This ensures successful boostrapping on the next startup\. The peer file is not written after at least 5 minutes of runtime\.
.
.P
Another source of peers is the local network\. KadNode can find peers via local peer discovery and bootstrap that way\. This is useful if the peers file only contains stale entries\.
.
.SH "AUTHENTICATION"
For most use cases you first need to create a secret/public key pair:
.
.IP "" 4
.
.nf

$kadnode \-\-auth\-genkey
public key: <public\-key>
secret key: <secret\-key>
.
.fi
.
.IP "" 0
.
.P
(The keys are not displayed here for convenience\.)
.
.SS "EXAMPLE 1"
A typical use case would be to reach a computer (Node1) from another (Node2)\. On Node 1 we announce an identifier (\fBsha1(myname)\fR): \fB$kadnode \-\-value\-id myname\.p2p\fR
.
.P
On other computers running KadNode, we can use myname\.p2p to resolve the IP address of Node1 (e\.g\. in the Browser)\. It may take ~8 seconds on the first try\. The problem with this approach is that others could also announce the same identifier\. This would result in multiple IP addresses to be found and used\. To avoid this you can use secret/public key pairs\. See the next examples\.
.
.SS "EXAMPLE 2"
Now we want to reach a computer (Node1) from another (Node2) using cryptographic keys\. We tell KadNode on Node1 to \fIannounce\fR its secret key\. \fB$kadnode \-\-value\-id <secret\-key>\.p2p\fR What is actually announced is the SHA1 hash of the derived public key (\fBsha1(<public\-key>)\fR), not the secret key itself\.
.
.P
On Node2, we can now resolve \fB<public\-key>\.p2p\fR\.
.
.SS "EXAMPLE 3"
Instead of using keys directly as in example 1, we can also use domains\.
.
.P
On Node1, well tell Kadnode to announce that we have node1\.p2p using the secret key\. \fB$kadnode \-\-auth\-add\-skey "node1\.p2p:<secret\-key>" \-\-value\-id node1\.p2p\fR The announced identifier here is \fBsha1(<public\-key>+"node1")\fR\.
.
.P
On Node2, we tell the node to use the public key to verifiy requests for node1\.p2p\. \fB$kadnode \-\-auth\-add\-pkey "node1\.p2p:<public\-key>"\fR The identifier that is searched for is \fBsha1(<public\-key>+"node1")\fR\.
.
.P
On Node2, we now can enter node1\.p2p into the browser or try to ping node1\.p2p to see if the address is resolved successfully\. The authentication step uses the public key to filter out all nodes that do not know the secret key\.
.
.SS "EXAMPLE 4"
Instead of just one name, it is possible to use patterns with a wildcard in front:
.
.P
Node1 will be reachable using node1\.p2p and foobar\.p2p\. \fB$kadnode \-\-auth\-add\-skey "*\.p2p:<secret\-key>" \-\-value\-id node1\.p2p \-\-value\-id foobar\.p2p\fR
.
.P
Node2 will be reachable using node2\.p2p and foobar\.p2p as well\. \fB$kadnode \-\-auth\-add\-skey "*\.p2p:<secret\-key>" \-\-value\-id node2\.p2p \-\-value\-id foobar\.p2p\fR
.
.P
On Node3, resolving "node1\.p2p", "node2\.p2p" and "foobar\.p2p" to its IP address should now work\. \fB$kadnode \-\-auth\-add\-pkey "*\.p2p:<public\-key>"\fR Since foobar\.p2p is used twice, KadNode will give both IP addresses\. But almost all programs will just use the first address they get, which is the first that will be successfully verified\.
.
.P
Multiple \-\-auth\-add\-key and multiple \-\-value\-id arguments are possible\. Pattern conflicts will result in an error message on startup\. Command line options can also be put inside a configuration file (see \-\-config \fIfile\fR)\.
.
.SH "IDENTIFIERS"
Identifiers are what you use to lookup IP addresses (e\.g\. "foo\.p2p")\. They will reduced to 20 Byte representations based on the SHA\-1 message digest algorithm\. The digest is what will be then used in the actual lookup process\. KadNode allows four types of identifiers:
.
.IP "\(bu" 4
Raw identifiers are 20 Byte identifiers written as hex strings\. No digest will be applied\.
.
.IP "\(bu" 4
E\.g: \fB<40_hex_characters>\.p2p\fR
.
.IP "" 0

.
.IP "\(bu" 4
Raw public key identifiers are 32 Byte hex strings\. They will be interpreted as a public key\.
.
.IP "\(bu" 4
The SHA\-1 digest of the key string respresentation is used to locate nodes\.
.
.IP "\(bu" 4
The public key is used to verify that the found nodes have the corresponding secret key\.
.
.IP "\(bu" 4
E\.g\.: \fB<64_hex_characters>\.p2p\fR
.
.IP "" 0

.
.IP "\(bu" 4
Plain identifiers are just strings that have no key associated to them\.
.
.IP "\(bu" 4
The SHA\-1 digest of the string is used to find nodes\.
.
.IP "\(bu" 4
E\.g\.: \fBexample\.p2p\fR
.
.IP "" 0

.
.IP "\(bu" 4
Plain identifiers that match a given pattern and have a public key assigned to them\.
.
.IP "\(bu" 4
The SHA\-1 digest of the string and public key is ued to find nodes\.
.
.IP "\(bu" 4
The public key is used to verify if the nodes found have the corresponding secret key\.
.
.IP "\(bu" 4
E\.g\.: \fBfoo\.p2p\fR
.
.IP "" 0

.
.IP "" 0
.
.P
All identifiers are converted to lowercase and are therefore case insensitive\. A "\.p2p" at the end of every identifier is ignored\. It is used to direct requests to KadNode\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-\-node\-id\fR \fIid\fR
.
.br
Set the node identifier\. This option is rarely needed\.
.
.br
By default the node id is random\.
.
.IP "\(bu" 4
\fB\-\-value\-id\fR \fIid[:port]\fR
.
.br
Add a value identifier and optional port to be announced every 30 minutes\.
.
.br
The announcement will associate this nodes IP address with this identifier\.
.
.br
This option may occur multiple times\.
.
.IP "\(bu" 4
\fB\-\-peerfile\fR \fIfile\-path\fR
.
.br
Import peers for bootstrapping and write good peers
.
.br
to this file every 24 hours and on shutdown\.
.
.IP "\(bu" 4
\fB\-\-user\fR \fIname\fR
.
.br
Change the UUID after start\.
.
.IP "\(bu" 4
\fB\-\-port\fR \fIport\fR
.
.br
Bind the DHT to this port (Default: 6881)\.
.
.IP "\(bu" 4
\fB\-\-config\fR \fIfile\fR
.
.br
Provide a configuration file with one command line
.
.br
option on each line\. Comments start after \'#\'\.
.
.IP "\(bu" 4
\fB\-\-ifname\fR \fIinterface\fR
.
.br
Bind to this specific interface\.
.
.IP "\(bu" 4
\fB\-\-fwd\-disable\fR
.
.br
Disable UPnP/NAT\-PMP to forward router ports\.
.
.IP "\(bu" 4
\fB\-\-daemon\fR
.
.br
Run in background\.
.
.IP "\(bu" 4
\fB\-\-query\-tld\fR \fIdomain\fR
.
.br
Top level domain used to filter queries to be resolved by KadNode\. (Default: "\.p2p")
.
.IP "\(bu" 4
\fB\-\-verbosity\fR \fIlevel\fR
.
.br
Verbosity level: quiet, verbose or debug (Default: verbose)\.
.
.IP "\(bu" 4
\fB\-\-pidfile\fR \fIfile\-path\fR
.
.br
Write process pid to a file\.
.
.IP "\(bu" 4
\fB\-\-lpd\-addr\fR \fIaddress\fR
.
.br
Send LPD packets to this multicast address as long no peers were found\.
.
.br
Default: 239\.192\.202\.7:6771 / [ff08:ca:07::]:6771
.
.IP "\(bu" 4
\fB\-\-lpd\-disable\fR
.
.br
Disable Local Peer Discovery (LPD)\.
.
.IP "\(bu" 4
\fB\-\-cmd\-disable\-stdin\fR
.
.br
Disable the local control interface\.
.
.IP "\(bu" 4
\fB\-\-cmd\-port\fR \fIport\fR
.
.br
Bind the remote control interface to this local port (Default: 1700)\.
.
.IP "\(bu" 4
\fB\-\-dns\-port\fR \fIport\fR
.
.br
Bind the DNS server to this local port (Default: 5353)\.
.
.IP "\(bu" 4
\fB\-\-nss\-port\fR \fIport\fR
.
.br
Bind the "Name Service Switch" to this local port (Default: 4053)\.
.
.IP "\(bu" 4
\fB\-\-web\-port\fR \fIport\fR
.
.br
Bind the web server to this local port (Default: 8053)\.
.
.IP "\(bu" 4
\fB\-\-auth\-gen\-keys\fR
.
.br
Generate a secret/public key pair\.
.
.IP "\(bu" 4
\fB\-\-auth\-add\-pkey\fR [\fIpattern\fR:]\fIpublic\-key\fR
.
.br
Associate a public key with any value id that matches the pattern\.
.
.br
Used to verify that the other side has the secret key\.
.
.br
This option can occur multiple times\.
.
.IP "\(bu" 4
\fB\-\-auth\-add\-skey\fR [\fIpattern\fR:]\fIsecret\-key\fR
.
.br
Associate a secret key with any value id that matches the pattern\.
.
.br
Used to prove the ownership of the domain\.
.
.br
This option can occur multiple times\.
.
.IP "\(bu" 4
\fB\-\-mode\fR \fIprotocol\fR
.
.br
Enable IPv4 or IPv6 mode for the DHT (Default: ipv4)\.
.
.IP "\(bu" 4
\fB\-h\fR, \fB\-\-help\fR
.
.br
Print the list of accepted options\.
.
.IP "\(bu" 4
\fB\-v\fR, \fB\-\-version\fR
.
.br
Print program version and included features\.
.
.IP "" 0
.
.SH "kadnode\-ctl"
\fBkadnode\-ctl\fR allows to control KadNode from the command line\.
.
.IP "\(bu" 4
\fB\-p\fR \fIport\fR
.
.br
The port used to connect to the command shell of a local KadNode instance (Default: 1700)\.
.
.IP "\(bu" 4
\fB\-h\fR
.
.br
Print this help\.
.
.IP "" 0
.
.SS "KadNode Console Commands"
.
.IP "\(bu" 4
\fBstatus\fR
.
.br
Print the node id, the number of known nodes / searches / stored hashes and more\.
.
.IP "\(bu" 4
\fBlookup\fR \fIquery\fR
.
.br
Lookup the IP addresses of all nodes that claim to satisfy the query\.
.
.br
The first call will start the search\.
.
.IP "\(bu" 4
\fBannounce\fR [\fIquery\fR[\fI:\fIport\fR\fR] [\fI\fIminutes\fR\fR]]
.
.br
Announce that this instance is associated with a query
.
.br
and an optional port\. The default port is random (but not equal 0)\.
.
.br
No \fIminutes\fR trigger a single announcement\. Negative \fIminutes\fR
.
.br
last for the entire runtime\. Otherwise the lifetime is set \fIminutes\fR into the future\.
.
.br
No arguments will announce all identifiers at once\.
.
.IP "\(bu" 4
\fBimport\fR \fIaddr\fR
.
.br
Send a ping to another KadNode instance to establish a connection\.
.
.IP "\(bu" 4
\fBexport\fR
.
.br
Print a few good nodes\.
.
.IP "\(bu" 4
\fBlist\fR [\fBblacklist\fR|\fBbuckets\fR|\fBconstants\fR|\fBforwardings\fR|\fBresults\fR|\fBsearches\fR|\fBstorage\fR|\fBvalues\fR]
.
.br
List various internal data structures\.
.
.IP "\(bu" 4
\fBblacklist\fR \fIaddr\fR
.
.br
Blacklist a specifc IP address\.
.
.IP "" 0
.
.SH "Web Interface"
The optional web interface allows queries of these forms:
.
.IP "\(bu" 4
\fBhttp://localhost:8053/lookup?foo\.p2p\fR
.
.IP "\(bu" 4
\fBhttp://localhost:8053/announce?foobar\fR
.
.IP "\(bu" 4
\fBhttp://localhost:8053/blacklist?1\.2\.3\.4\fR
.
.IP "" 0
.
.P
If the interface cannot be reached then the interface might be disabled (port set to 0) or not compiled in (check \fBkadnode \-\-version\fR)\. In case the IPv6 entry for localhost is not used or missing, try \fB[::1]\fR instead of \fBlocalhost\fR\.
.
.SH "PORT FORWARDINGS"
If KadNode runs on a computer in a private network, it will try to establish a port forwarding for the DHT port\. Port forwarding only works if UPnP/NAT\-PMP is compiled into KadNode and is supported by the gateway/router\. Also, ports attached to announcement values (e\.g\. \fB\-\-value\-id foo\.p2p:80\fR) will result in additional port forwardings\. This is useful to make a local service (e\.g\. a web server) reachable from the Internet without the need to configure port forwardings manually\.
.
.SH "NOTES"
.
.IP "\(bu" 4
\fI\.p2p\fR at the end of an identifier (or set by \-\-query\-tld) is ignored by KadNode\. It is used to filter requests and divert them to KadNode\.
.
.IP "\(bu" 4
The interfaces (NSS, DNS, command line) may return the localhost address if the node itself announced a value\.
.
.IP "" 0
.
.SH "LICENSE"
MIT/X11
.
.SH "AUTHORS"
.
.IP "\(bu" 4
KadNode: Moritz Warning (http://github\.com/mwarning)
.
.IP "\(bu" 4
Kademlia: Juliusz Chroboczek
.
.IP "\(bu" 4
SHA\-1: Steve Reid
.
.IP "" 0

